const OrmActionTypes = {
  TOGGLE_TAG: 'TOGGLE_TAG',
  TOGGLE_LEVEL: 'TOGGLE_LEVEL',
  ADD_TAG_TO_WCAG: 'ADD_TAG_TO_WCAG',
  DELETE_TAG_FROM_WCAG: 'DELETE_TAG_FROM_WCAG',
};

export default OrmActionTypes;
